### ISSUE TITLE
Actions Plot: The missing actions should be displayed below the main plot area within corresponding stages with hover over effect displaying the missing action comment

### ISSUE THREAD

**Issue by gunalmel** [gunalmel/mteam-dashboard#20]
We discussed how to display missing actions. 
1. Use popup on plot area to display all missing action information as text within popup window.
2. Use a table below the chart area to display all the missing actions in a column corresponding to another column that will list stages/phases.
3. Use the original design where the stages are extended below the char to formerly display required actions' images.

Kerim dismissed option 3 thinking that fitting all missing actions' icons may not be possible if some stages are very narrow. As we explored options 1 & 2 we thought it would be less time-consuming to try expanding the height of the plot area below the main plot area to accommodate icons in multiple rows. The reasoning is that the existing code would be easier to tweak rather than writing new code and mange the styling to work nicely on the screen. 

P.S.: The 3rd option was favored by Vitali and his ER contact providing feedback on how to visualize actions data. However, when Kerim mentioned popup idea Vitaliy approached it positive in his email 09/04.

**Comment by kalibrain** [comment]
I have implemented the following updates based on our discussions:

-  Popup Information: A popup feature has been added to the plot area to display all missing action information as text when hovered on error images. Images will be provided later. Currently it shows a default "X" image for unidentified actions.

- Missing Actions (Triggered Errors) Plot Area: Kept the size of the missing actions area. I may adjust it later to accommodate more missing action items if needed.
