### ISSUE TITLE
Actions Plot: Trainees should be able to see the state transitions so that they can identify the time blocks that identify vital states

### ISSUE THREAD

**Issue by gunalmel** [gunalmel/mteam-dashboard#4]
<img src="https://private-user-images.githubusercontent.com/1005066/343761474-bb05a8a5-3d87-4c55-8a46-dd9058e9a66d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTc4NTAsIm5iZiI6MTcxOTQ5NzU1MCwicGF0aCI6Ii8xMDA1MDY2LzM0Mzc2MTQ3NC1iYjA1YThhNS0zZDg3LTRjNTUtOGE0Ni1kZDkwNThlOWE2NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMTQxMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI1NGFhMzZiZTM3YzFjYjZkYzkxNWM5Zjk0OGRhODk2ZTcwZTQxODA0ZGY3Y2FmOTVmMzA5ZTkyNGQ1YjUxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NM7PIgSsoUbSP5RgHzAT5bn_NDK6owp-1o3LqoyDfws"/>

Scatter plot has color shaded areas that shows state transitions. In #2 those areas are hard coded to find out how to implement shaded areas on scatter plot using [plotly.js](https://plotly.com/javascript/) 

![image](https://github.com/user-attachments/assets/115ac293-c7bb-42ac-acb6-0af3c6b1359a)

## User Story 

```gherkin
Feature: Trainees should be able to see the state transitions on clinical review timeline chart so that they can identify the time blocks that identify vital states
Scenario: Trainees view the clinical review timeline chart to identify state transitions
    Given the trainee is on dashboard
     When the scatter plot of actions, compression periods are plotted on a timeline
     Then the chart (plot area) should be divided into color coded blocks that identify state transitions as specified by the rules to parse the csv data for the boundaries of transitions.
```
## References

[Requirements](../wiki/Requirements#how-to-identify-transitions-in-virtual-reality-training-data-in-csv-format-actions--compressions)

**Comment by gunalmel** [comment]
I used the code in the demo app at https://github.com/thedevagyasharma/mteam-dashboard to display the transition areas on the graph. The first 2 transitions overlapped and there are gaps which makes me think that it does not correspond to the rules in the requirements (follow the link in the issue body's references). 

isTransitionBoundary function in dashboard/page.tsx controls the boundaries for transitions.

**Comment by gunalmel** [comment]
We have a problem with Vercel. React plotly component doesn't render the chart correctly. https://mteam-dashboard.vercel.app/dashboard displays the chart without data points or transitions and a trace line legend on the left hand side.

**Comment by gunalmel** [comment]
You can reproduce the problem after being deployed to https://mteam-dashboard.vercel.app/dashboard  by running build first and then running in prod mode:
npm run build
npm start

https://plotly.com/javascript/react/ may be helpful in troubleshooting

**Comment by gunalmel** [comment]
Turned out that the problem was with the webpack minification during production build. Modified webpack build optimization (minification) to use TerserPlugin which fixed the problem of plotly not rendering the chart correctly. Turning off the minification could also work.

Turning off it in next.config.js
```js
// next.config.js
module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    if (!dev) {
      config.optimization.minimize = false;
    }
    return config;
  },
};
```
configuring TerserPlugin to modify minification process

```js
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  webpack: (config, { dev, isServer }) => {
    if (!dev && !isServer) {
      config.optimization.minimizer = [
        new TerserPlugin({
          terserOptions: {
            mangle: false,
            keep_classnames: true,
            keep_fnames: true,
          },
        }),
      ];
    }

    return config;
  },
};
```

**Comment by kalibrain** [comment]
> I used the code in the demo app at https://github.com/thedevagyasharma/mteam-dashboard to display the transition areas on the graph. The first 2 transitions overlapped and there are gaps which makes me think that it does not correspond to the rules in the requirements (follow the link in the issue body's references).
> 
> isTransitionBoundary function in dashboard/page.tsx controls the boundaries for transitions.

I don't see any specific requirement stating that there will be no overlapping stages or no gap in between stages. Code seems to be finding the stages appropriately.

**Comment by kalibrain** [comment]
Tested the code using the local timeline-multiplayer CSV file provided by Vitaliy in dropbpx. While there are still some gaps between game stages, the issue of overlapping stages didn't occur. See the output image below.

![Screen Shot 2024-07-02 at 10 35 02 PM](https://github.com/gunalmel/mteam-dashboard/assets/9113083/defd9c79-eb58-43b5-ad11-8d02758b8f86)

**Comment by gunalmel** [comment]
We'd better annotate the beginning and end of transitions and let clicking on borders to scroll within the video
