### ISSUE TITLE
Visual Attention: Update the colors for categories. Ensure consistent colors and object order in the fixation graph legend across all user roles

### ISSUE THREAD

**Issue by gunalmel** [gunalmel/mteam-dashboard#40]
3rd bullet point from Min Park - [phyunmin@umich.edu](mailto:phyunmin@umich.edu) on Nov 14, 2024 Thursday:
[Month 6th November Updates](../wiki/Month-6th-November-Updates)
**Consistent Legend Colors and Order:** Ensure consistent colors and object order in the fixation graph legend across all user roles:

- Tablet: Grey
- Patient: Red
- Team: Blue
- Equipment: Yellow
- Monitor: Green
- Other: Purple

**Comment by kalibrain** [comment]
Implemented color-coding for each VisualAttention category in constants.ts and updated processGazeData.ts to apply these colors consistently in Plotly bar charts. Ensured a uniform category order in the plot data and modified VisualAttentionPlot.tsx to reflect the desired category sequence in the legend.

Replaced the colors specified in the ticket with pastel shades for a softer and visually appealing look.

Effort: 1 hr
