### ISSUE TITLE
Visual Attention: When hovering over the bar chart, display the specific object IDs instead of the categories

### ISSUE THREAD

**Issue by gunalmel** [gunalmel/mteam-dashboard#42]
6th bullet point from Min Park - [phyunmin@umich.edu](mailto:phyunmin@umich.edu) on Nov 14, 2024 Thursday:
[Month 6th November Updates](../wiki/Month-6th-November-Updates)

**Tooltip Object ID Display:** When hovering over the bar chart, display the specific object IDs instead of the categories. For example, in cases like:

- {"time": 1727713674.8, "object": "Pump_Mask_Interactable_R(Clone)", "category": "Equipment"}
- {"time": 1727713675.0, "object": "Defibrillator", "category": "Equipment"}

The tooltip should show “Pump_Mask_Interactable_R(Clone)” and “Defibrillator” when hovering over the respective bars.

**Comment by kalibrain** [comment]
Updated the processGazeData function to track unique objects alongside category counts within sliding windows. Updated corresponding tests and types to support the new functionality, and adjusted the transformGazeDataForPlotly function to include hover text with object details. See screenshot below to see an example of hovertext.

![Screenshot 2024-11-19 at 12 17 23 AM](https://github.com/user-attachments/assets/c1374d78-bdf0-4f12-8741-1c1b875b41ab)

Effort: 2 hrs
